routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('search')->group(function() {
    Route::get('/', 'SearchController@index')->name('search');
    Route::get('find', 'SearchController@find');
    // Route::get('', 'SearchController@search')->name('search.search');
});

Route::prefix('books')->group(function() {
    Route::get('/', 'BooksController@index')->name('books');
    Route::get('{id}', 'BooksController@detail')->name('books.detail');
});


Route::prefix('admin')->namespace('Admin')->middleware('auth')->group(function() {
    Route::get('/', 'DashboardController@index')->name('admin');
    Route::prefix('authors')->group(function() {
        Route::get('/', 'AuthorsController@index')->name('admin.authors');
        Route::get('{id}', 'AuthorsController@detail')->name('admin.author.detail');
        Route::post('create', 'AuthorsController@create')->name('admin.authors.create');
    });
    Route::prefix('books')->group(function() {
        Route::get('/', 'BooksController@index')->name('admin.books');
        Route::get('archive', 'BooksController@archive')->name('admin.books.archive');
        Route::get('{id}', 'BooksController@detail')->name('admin.books.detail');
        Route::delete('{id}', 'BooksController@delete')->name('admin.books.delete');
        Route::post('archive/{id}', 'BooksController@restore')->name('admin.books.restore');
        Route::delete('archive/{id}', 'BooksController@hardRemove')->name('admin.books.hard-remove');
    });
    Route::prefix('publishers')->group(function() {
        Route::get('/', 'PublishersController@index')->name('admin.publishers');
        Route::get('{id}', 'PublishersController@detail')->name('admin.publishers.detail');
    });
    Route::prefix('tags')->group(function() {
        Route::get('/', 'TagsController@index')->name('admin.tags');
        Route::post('add', 'TagsController@add')->name('admin.tags.add');
    });
    Route::prefix('dbdump')->group(function() {
        Route::get('/', 'DbDumpController@index')->name('admin.dbdump');
        Route::post('/', 'DbDumpController@dump')->name('admin.dbdump');
        Route::get('download', 'DbDumpController@download')->name('admin.dbdump.download');
    });
});

Route::prefix('php-learning')->namespace('Admin')->group(function() {
    Route::get('/', 'ParserController@index')->name('admin.parser');
    Route::post('a', 'ParserController@parseAuthors')->name('admin.parse.authors');
    Route::get('a/test', 'ParserController@receiveAuthor');
    Route::get('b/test', 'ParserController@receiveBook');
    Route::get('p/test', 'ParserController@receivePublisher');
});

app/Models/Book.php
<?php

namespace App\Models;
use Nicolaslopezj\Searchable\SearchableTrait;

class Book extends \App\Models\Base\Book
{
	use SearchableTrait;

    protected $searchable = [
        'columns' => [
            'books.name' => 10,
            // 'authors.name' => 5,
            // 'publishers.name' => 3,
        ],
        // 'joins' => [
        //     'authors' => ['users.id','authors.user_id'],
        // ],
    ];

	protected $fillable = [
		'name',
		'author_id',
		'original_name',
		'format',
		'pages',
		'year',
		'publisher_id',
		'cover',
		'ozon_id',
	];

	public function getOzonUrlAttribute()
	{
		if (empty($this->ozon_id)) {
			return false;
		}
		return \App\Utilities\OzonSettings::getUrlWithId('books', $this->ozon_id);
	}

	public function authorsNames($withLink = false)
	{
		$names = [];
		$authors = $this->authors()->get();
		foreach ($authors as $author) {
			$names[] = $withLink
				? '<a href="/admin/authors/' . $author->id . '/">' . $author->name . '</a> '
				: $author->name;
		}
		return implode(', ', $names);
	}

	public function publishersNames($withLink = false)
	{
		$names = [];
		$publishers = $this->publishers()->get();
		foreach ($publishers as $publisher) {
			$names[] = $withLink
				? '<a href="/admin/publishers/' . $publisher->id . '/">' . $publisher->name . '</a> '
				: $publisher->name;
		}
		return implode(', ', $names);
	}
}

resources/views/admin/detail/author.blade.php
@extends('layouts.admin')

@section('content')
    @if (empty($author))
        <div class="jumbotron">
            <h2 class="display-4">Автор не найден</h2>
            <p>Ошибка 404</p>
        </div>
    @else
        <div class="jumbotron">
            <h2 class="display-4">{{ $author->name }}</h2>
            <p>Автор</p>
            <hr class="my-4">
            <p class="lead">ФИО: {{ $author->name }}</p>
            <p class="lead">Озон: <a href="{{ $author->ozon_url }}">{{ $author->ozon_url }}</a></p>
        </div>
        @if ($author->books()->get())
        <p>Книги автора</p>
        <div class="row">
            @foreach ($author->books()->get() as $index => $book)
            <div class="col-sm-4 col-md-2">
                <div class="thumbnail">
                    <img style="width: 100%" src="{{ $book->cover }}" alt="{{ $book->name }}">
                    <div class="caption">
                        <h3>{{ $book->name }}</h3>
                        <p><small>{{ $book->authorsNames() }}</small></p>
                        <p>{{ $book->description }}</p>
                        <p><a href="/admin/books/{{ $book->id }}/" class="btn btn-primary" role="button">Перейти</a></p>
                    </div>
                </div>
            </div>
            @if ($index % 4 == 3)
        </div>
        <div class="row">
            @endif
            @endforeach
        </div>
        @else
        <p>Книг у автора не найдено</p>
        @endif
    @endif
@endsection

resources/views/admin/detail/book.blade.php
@extends('layouts.admin')

@section('content')
    @if (empty($book))
        <div class="jumbotron">
            <h2 class="display-4">Книга не найдена</h2>
            <p>Ошибка 404</p>
        </div>
    @else
        <div class="jumbotron">
            <h2 class="display-4">{{ $book->name }}</h2>

            <hr class="my-4">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="media">
                        <div class="media-left">
                            <img class="zoom" style="max-width: 10em;" src="{{ $book->cover }}" alt="{{ $book->name }}">
                        </div>
                        <div class="media-body">
                            <dl class="dl-horizontal">
                                <dt>Название:</dt>
                                <dd>{{ $book->name }}</dd>
                                <dt>Оригинальное название:</dt>
                                <dd>{{ $book->original_name }}</dd>
                                <dt>Авторы:</dt>
                                <dd>{!! $book->authorsNames(true) !!}</dd>
                                <dt>Издатели:</dt>
                                <dd>{!! $book->publishersNames(true) !!}</dd>
                                <dt>Формат:</dt>
                                <dd>{{ $book->format }}</dd>
                                <dt>Кол-во страниц:</dt>
                                <dd>{{ $book->pages }}</dd>
                                <dt>Год:</dt>
                                <dd> {{ $book->year }}</dd>
                                <dt>Озон:</dt>
                                <dd><a  class="btn btn-primary" href="{{ $book->ozon_url }}">Открыть</a></dd>
                            </dl>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    @endif
@endsection

resources/views/admin/detail/publisher.blade.php
@extends('layouts.admin')

@section('content')
    @if (empty($publisher))
        <div class="jumbotron">
            <h2 class="display-4">Издатель не найден</h2>
            <p>Ошибка 404</p>
        </div>
    @else
        <div class="jumbotron">
            <h2 class="display-4">{{ $publisher->name }}</h2>
            <p>Издатель</p>
            <hr class="my-4">
            <p class="lead">Название: {{ $publisher->name }}</p>
            <p class="lead">Озон: <a href="{{ $publisher->ozon_url }}">{{ $publisher->ozon_url }}</a></p>
        </div>
        @if ($publisher->books()->get())
        <p>Книги издателя</p>
        <div class="row">
            @foreach ($publisher->books()->get() as $index => $book)
            <div class="col-sm-4 col-md-2">
                <div class="thumbnail">
                    <img style="width: 100%" src="{{ $book->cover }}" alt="{{ $book->name }}">
                    <div class="caption">
                        <h3>{{ $book->name }}</h3>
                        <p><small>{{ $book->authorsNames() }}</small></p>
                        <p>{{ $book->description }}</p>
                        <p><a href="/admin/books/{{ $book->id }}/" class="btn btn-primary" role="button">Перейти</a></p>
                    </div>
                </div>
            </div>
            @if ($index % 4 == 3)
        </div>
        <div class="row">
            @endif
            @endforeach
        </div>
        @else
        <p>Книг у автора не найдено</p>
        @endif
    @endif
@endsection